name: Auto Enroll Udemy Courses

on:
  schedule:
    # 每天 UTC 00:00 執行（可以根據需要調整）
    - cron: '0 15 * * *'
  # 允許手動觸發
  workflow_dispatch:

jobs:
  enroll:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run enrollment script
      env:
        UDEMY_EMAIL: ${{ secrets.UDEMY_EMAIL }}
        UDEMY_PASSWORD: ${{ secrets.UDEMY_PASSWORD }}
      run: |
        python cli.py